pyall/analysis-2015_03/meta.yaml

I don't think we need this installed by default. It is *probably* a dead project. Too soon to nuke the album recipe entirely though.

Remove album from analysis metapkg.

---

docker/Dockerfile
nonpy/ncurses-5.9/build.sh
nonpy/ncurses-5.9/meta.yaml

I'm bumping the build number so that this *should* automatically replace any builds with build_number = 7, which apparently are segfaulting!
cc @tacaswell

MNT: Re-introduce configure flag to ncurses

---

pyall/metadatastore-0.4.1/build.sh
pyall/metadatastore-0.4.1/config.patch
pyall/metadatastore-0.4.1/meta.yaml

Note: we never made one for v0.4.0, tagged six days ago, but there's no practical reason to go back for it. v0.4.1 has important fixes.

Add metadatastore v0.4.1

---

nonpy/config-dev/build.sh
nonpy/config-dev/meta.yaml
nonpy/config-dev/pre-unlink.sh

attn @tacaswell Any reason why this is a bad idea?  I keep getting issues
where the config cannot seem to load values out of the specified 
configuration file location and it greatly annoys me. This fixes that by 
just using env vars. 
Also note the addition of the pre-unlink.sh script that will remove those
two files if/when this package is removed. We should be more careful about
keeping track of the files that we add with our conda packages and clean 
up after ourselves when those packages are removed.

ENH: Use env vars for dev configuration

---

recipes-tag/event-model/meta.yaml

We were missing an event-model recipe in recipes-tag. This adds one for the newly-tagged v1.1.0.

Add event-model tagged recipe.

---

recipes-dev/amostra/meta.yaml
recipes-dev/metadataclient/meta.yaml
recipes-dev/metadataservice/meta.yaml

The recipes in -tag folder can be shipped to conda-forege again. We will keep -dev.

DEV: meta file to dev folder

---

recipes-dev/bluesky/meta.yaml
recipes-dev/metadatastore/meta.yaml
recipes-tag/bluesky/meta.yaml
recipes-tag/databroker/meta.yaml
recipes-tag/pyxrf/meta.yaml
scripts/build.py
scripts/nsls2-dev-build.sh
scripts/nsls2-tag-build.sh
scripts/tail-tag-log

also corrected sha256 number, and remove unused tests.

Fix issue due to Conda-forge

---

metapackages/analysis/meta.yaml
metapackages/collection/meta.yaml

This PR adds metapackages, similar to conda's `environment.yml` idea but with slightly different feature set. We tried this once before and abandoned it. Maybe it will stick this time.
* The `analysis` metapackage contains most of our stuff, including bluesky because the callbacks are useful on saved data.
* The `collection` metapackage depends on the `analysis` one, and it adds ophyd and pyolog.
* The version scheme is not semantic versioning: it is the date plus a micro version for corrections (e.g., `2016-09-29.0`.

Add metapackages for collection, analysis.

---

recipes-tag/03-ID-HXN-collection/meta.yaml
recipes-tag/04-ID-ISR-collection/meta.yaml
recipes-tag/05-ID-SRX-collection/meta.yaml
recipes-tag/11-ID-CHX-analysis/meta.yaml
recipes-tag/16-ID-LIX-analysis/meta.yaml
recipes-tag/23-ID-1-CSX1-analysis/meta.yaml
recipes-tag/23-ID-1-CSX1-collection/meta.yaml
recipes-tag/23-ID-2-CSX2-analysis/meta.yaml

Decisions implicit in this PR:
* At the beginning of each cycle, beamlines will get the standard analysis and collection metapackages and, if applicable, beamline-specific BL-analysis and BL-collection metapackages.
* We will only create these BL-* metapackages as needed. We will not create a pile of empty "placeholder" metapackages for the beamlines that don't have any extra dependencies yet.
* The BL-* metapackages do not necessarily depend on the standard analysis/collection packages, though they may (e.g., if they need to pin to certain version).
* The BL-* metapackages will be versioned using the same scheme used by the standard metapackages. They may not need to be upgraded every cycle, but that is fine.

Add beamline-specific metapackages for beamlines with extra deps.

---

recipes-tag/08-id-iss-analysis/meta.yaml
recipes-tag/isstools/meta.yaml

Update to isstools v0.3 (just tagged) and add deps that were missing and being manually installed. Some of these deps aren't packaged yet:

Update isstools and add misisng deps.

---

recipes-tag/pyfai/meta.yaml

Copied without modifcation from conda-forge. It targets v0.13.0, which is their latest tag.

Add pyfai recipe from conda-forge.

---

recipes-tag/databroker/meta.yaml

attn @licode This just removes that extra dep (but we probably still need to package it).

MNT: drop extra dependencies from databroker

---

recipes-tag/analysis/meta.yaml

this will not be included in analysis. But we will still add it to -tag for individual application.

remove ipyvolume

---

scripts/nsls2-dev-build.sh

still pin conda-build and conda-env. Just keep recond here. We may update those numbers accordingly later.

DEV: conda build 3

---

recipes-tag/pychx/meta.yaml

@mrakitin and I had to make some fixes to pyCHX. we updated version number:
https://github.com/NSLS-II-CHX/pyCHX/releases/tag/v2.0.2
(PR: https://github.com/NSLS-II-CHX/pyCHX/pull/14)

updated pyCHX

---

recipes-tag/analysis/meta.yaml
recipes-tag/collection/meta.yaml

Note that the _environments_ installed this cycle have already been manually
updated to use the new naming scheme. This change makes the names of the metapackages
consistent. It will intentionally cause the builder to build a 2018-1.0 version
that is identical to the 18Q1.0 version.

Apply new naming scheme.

---

recipes-tag/23-id-2-csx2-analysis/meta.yaml
recipes-tag/23-id-2-csx2-collection/meta.yaml

CSX2 needs amostra. tested using `conda build -c lightsource2-tag`
will also add to playbooks

Added amostra to csx2

---

recipes-tag/py4xs/meta.yaml

Lin Yang has requested we add py4xs.
> Just want to mention that we use py4xs (it's on pypi but not on github) for data processing and it would be nice to have it next time when you update the conda environment.
It's not on github, so we have to use pypi

Added py4xs

---

recipes-tag/isstools/meta.yaml

isstools uses qt5 : https://github.com/NSLS-II-ISS/isstools/blob/master-qt5/isstools/gui.py

Change isstools to qt5

---

recipes-tag/isstools/meta.yaml

@danielballan forgot to inc build number...
but did test it works. i did a **very** dirty upload just to test:
`anaconda upload -u lightsource2-tag ~/anaconda3/conda-bld/linux-64/isstools-1.3-0.tar.bz2 --force`

inc build number

---

recipes-tag/12-id-smi-analysis/meta.yaml
recipes-tag/12-id-smi-collection/meta.yaml

Fixing the `-` separator issue for #294.

SMI extra-packages: fixed version separator to make conda happy

---

recipes-tag/epics-base/meta.yaml

test purposes. @tacaswell  
previous version is not from author lightsource2-tag, https://conda.nsls2.bnl.gov/nsls2-tag/epics-base/files

rebuilt epics base without readline

---

recipes-tag/hkl/meta.yaml
recipes-tag/hklpy/meta.yaml

hkl requires gsl==2.2.1 as it looks for a specific library file (libgsl.so.19).
We can recompile hkl to use the newer version of gsl (2.4) later. But for now, it is a good idea to keep this dependency, or else we'll see an error of the form (as conda will install the latest version by default):
```
Error: g-invoke-error-quark: Could not locate hkl_factories: libgsl.so.19: cannot open shared object file: No such file or directory 
```

Update hkl requirements

---

recipes-tag/hklpy/meta.yaml

We're now at v0.3.12.
This could also be considered v0.4. We change minor number when a new feature is added that is backwards compatible. Since the limits never really worked, this could also be considered a feature.
I'll keep as v0.3.12 (so just change the patch number) but can change ti v0.4 if someone has a different opinion.

updated hkl version

---

recipes-tag/pyzbar/build.sh
recipes-tag/pyzbar/meta.yaml
recipes-tag/pyzbar/run_test.py

Should be merged along with #311.
Both zbar and pyzbar packages were successfully built and tested locally on https://hub.docker.com/r/nsls2/debian-with-miniconda/.

pyzbar wrapper of zbar lib

---

recipes-tag/23-id-1-csx1-collection/meta.yaml

We should enforce hkl>=0.3.12 from now on for CSX (and other beamlines eventually)

Strict version on hkl for csx

---

recipes-tag/h5py/meta.yaml

This will let us use numpy 1.14 on the floor this cycle

BLD: update to h5py 2.8.0

---

recipes-tag/08-id-iss-analysis/meta.yaml

the name of the iss package is inconsistent with our current convention

Fix iss tag

---

recipes-tag/collection/meta.yaml

I think this is a useful library for the beamline as a whole. CHX needed it yesterday (#314) but I think we could maybe just make this a facility wide dep.
This allows scientists to quickly integrate serial devices into their beamlines, which can be a useful thing to do once in a while.
If this is merged, don't merge #314

add pyserial to collection env

---

recipes-tag/pysmbc/meta.yaml

This solves the issue with building of the pysmbc package.
**Limitations:**
- I had to remove the `test` section, since it required the `smbclient` library to be installed in advance. We either need to build it separately, or assume it's already installed on a target machine.

Fix pysmbc package

---

recipes-tag/pypdf2/meta.yaml

Tested locally, already uploaded the package: https://anaconda.org/lightsource2-tag/pypdf2/files

Fix pypdf2 tagging scheme

---

recipes-tag/pyxrf/meta.yaml
recipes-tag/scikit-beam/meta.yaml

This leaves it up to the individual beamlines whether to pin lmfit to 0.8.3 and
get working xrf code in scikit-beam or accept broken xrf code in scikit-beam in
order to use Larch and modern lmfit.
The ideal fix would be to update the xrf code in scikit-beam, but that update
is not straightforward, and we cannot wait for it.
Closes https://github.com/NSLS-II/lightsource2-recipes/issues/349
Punts on the underlying issue, which is tracked over at scikit-beam:
https://github.com/scikit-beam/scikit-beam/issues/448

Move lmfit pin from scikit-beam to pyxrf.

---

recipes-tag/12-id-smi-collection/meta.yaml
scripts/bootstrapping/bootstrap-dev-build
scripts/bootstrapping/bootstrap-tag-build
scripts/build.py
scripts/nsls2-tag-build.sh

I propose a new building approach -- one package per docker container.
- One package per docker container, meaning complete isolation of building process of each package.
- Each docker container is named now (the format is `<package_name>-<%Y%m%d%H%M%S>`), which means we can better monitor what's building at any given moment by `docker ps -a`.
- Avoid a long operation of bulk testing of the builds/versions of _all_ the packages (around 130!) before actual build starts -- it takes about 30 minutes with the old approach. This is achieved by the configurable period of time (2 days by default) to look back in git log that allows us to build just those packages which were recently updated.
- Possible overhead related to recreation of the whole conda environment (takes ~1 minute per package), …

ENH: improve building workflow

---

scripts/nsls2-tag-build.sh

... to avoid overwhelming of freyja
Cron job is currently configured to run every 15 minutes. No updates on freyja needed after merging, the code will be picked directly from GH.

Reduce the time horizon from 2 days to 30 minutes

---

recipes-tag/analysis/meta.yaml

A few users (including myself) encountered the situation when attempting to read or write Excel files with pandas, but critical dependencies are missing. Adding it here.
Attn @awalter-bnl, @tacaswell.

Add xlrd (Excel reading) and xlwt (Excel writing) libs to analysis package

---

recipes-tag/srw/meta.yaml

Building https://github.com/radiasoft/SRW-light/releases/tag/v0.0.2.

SRW: bump version to v0.0.2 to follow up recent updates

---

recipes-tag/18-id-fxi-collection/meta.yaml

Installed manually at the beamline for now (xf18id-ws2), needs to be deployed automatically during the next deployment.

FXI: add pypdf2

---

recipes-tag/analysis/meta.yaml

FFmpeg may be useful at many beamlines, so I propose we include
it in the next roll out (likely 2018-2.2).

Add FFmepg to standard analysis metapackage.

---

recipes-tag/caproto/meta.yaml

We caught a simple bug in caproto-shark at SIX today. Made a small release to
get it out in time for our rollout.

Bump caproto to 0.3.2.

---

recipes-tag/event-model/meta.yaml

v1.8.1 has a known issue was intentionally skipped.

Bump version of event-model to 1.8.2.

---

recipes-tag/hdf5-lz4/meta.yaml
recipes-tag/lz4-c/meta.yaml

Fixing a mistake a merged too quickly in #531. This now pins in exactly
the same way that the analysis metapackage pins it.

FIX: Pinning specification had wrong syntax.

---

recipes-tag/databroker-elasticsearch/meta.yaml

Update dbes to its latest version.
cc: @linepouchard

Bump databroker-elasticsearch to 0.0.2

---

recipes-tag/analysis/meta.yaml

We need bluesky and ophyd tagged as shown in this PR first

BLD: update analysis for 2019C3

---

recipes-tag/bluesky-browser/meta.yaml
recipes-tag/intake-bluesky/meta.yaml

I got a conflict report on docker that `msgpack` using v0.2.3 which require python 2.7. 
I assume this could be fixed when conda find msgpack on defaults channel.

BLD: Add bluesky-browser and intake-bluesky

---

intake/LICENSE
intake/meta.yaml

This was copy paste from here. https://github.com/conda-forge/intake-feedstock/tree/master/recipe
python-snappy was removed for solving conflict with analysis. python-snappy is a optional package for intake.

BLD: Add intake without dependency python-snappy

---

recipes-tag/02-id-six-analysis/meta.yaml

Bump build number of 02-id-six-collection to include pycentroids

---

.travis.yml
recipes-tag/xrt/entry-points.patch
recipes-tag/xrt/meta.yaml

Initial version of `xrt` recipe.
It can optionally use `pyopencl` at runtime, so I am not sure whether to make it a hard requirement or not as the package can run without it.  
fixes #675

Initial version of recipe for xrt

---

recipes-tag/nslsii/meta.yaml

Edited by @mrakitin: it's a mirror update of https://github.com/nsls-ii-forge/nslsii-feedstock/pull/4.

Bump nslsii to 0.0.12.

---

recipes-tag/lmfit-c/meta.yaml

@mrakitin The error with #818 was due to `lmfit-c` needing to be revved. This pull does that.

Reved version of lmfit to master on NSLS-II
