NSLS-II/lightsource2-recipes

- pyall/analysis-2016_01/meta.yaml
- pyall/collection-2016_01/meta.yaml
These are just suggestions. See commit msgs for rationales. There no glaring issues as far as I can see, so good work. I just went through setting up the collection env manually with @hhslepicka today, so the requirements are fresh in my mind.
> Fixup metapkgs

- nonpy/hdf5-lza-0.2/build.sh
- nonpy/hdf5-lza-0.2/meta.yaml
This is needed to read eiger/dectris hdf5 files.
> ENH: add hdf5-lz4

- pyall/doct-1.0.2/build.sh
- pyall/doct-1.0.2/meta.yaml
I just tagged v1.0.2 of doct (with pickling support).
> Add doct 1.0.2

- pyall/analysis-2016_01/meta.yaml
Per discussed with @ericdill, made amostra part of collection and analysis environments until a server conda env is in place.
> MNT:Added amostra to auto-build.Both client and server is in the same package

- recipes-tag/bluesky/meta.yaml
- recipes-tag/databroker/meta.yaml
- recipes-tag/metadatastore/meta.yaml
- recipes-tag/ophyd/meta.yaml
- recipes-tag/suitcase/meta.yaml
> DEV: update on meta files

- recipes-tag/metadataclient/meta.yaml
@licode Could you take a look at this?
> ENH:Add metadataclient recipe

- recipes-tag/isstools/meta.yaml
> DEV: isstools added

- recipes-dev/metadataservice/meta.yaml
- recipes-tag/metadataservice/meta.yaml
> MNT:Add missing mds requirement to mdservice conda recipes

- recipes-tag/amostra/meta.yaml
- recipes-tag/databroker/meta.yaml
- recipes-tag/event-model/meta.yaml
- recipes-tag/metadataclient/meta.yaml
- recipes-tag/metadatastore/meta.yaml
filestore is done, bluesky will be considered later.
> REL: for release of 17Q1

- metapackages/analysis/meta.yaml
- metapackages/collection/meta.yaml
> update collection and analysis to 17Q1.0

- recipes-tag/11-id-chx-analysis/meta.yaml
- recipes-tag/11-id-chx-collection/meta.yaml
@yugangzhang Please confirm that these two metapackages includes everything you need for collection and analysis, respectively.
> Add CHX collection metapkg and require 'chxanalys' package for analysis.

- recipes-tag/ophyd/meta.yaml
a lots of change since old version.
> ophyd v0.5.0

- recipes-tag/event-model/meta.yaml
> MNT: fix event-model recipe

- recipes-tag/boltons/meta.yaml
> add boltons feedstock

- recipes-tag/atom/bld.bat
- recipes-tag/atom/build.sh
- recipes-tag/atom/meta.yaml
- recipes-tag/enaml/bld.bat
- recipes-tag/enaml/build.sh
- recipes-tag/enaml/meta.yaml
- recipes-tag/kiwisolver/bld.bat
- recipes-tag/kiwisolver/build.sh
- recipes-tag/kiwisolver/meta.yaml
> BUG: better version of enaml

- recipes-tag/enaml/meta.yaml
- recipes-tag/enaml/mpl_qt5.patch
Opening PR upstream, this will be able to be dropped soon
> ENH: add patch to enaml to support qt5

- recipes-tag/scikit-beam/meta.yaml
- recipes-tag/xraylib/build.sh
- recipes-tag/xraylib/meta.yaml
> xraylib, and new version for skbeam

- recipes-tag/analysis/meta.yaml
- recipes-tag/collection/meta.yaml
- scripts/nsls2-tag-build-local.sh
> DEV: new envs for 2017Q2

- recipes-tag/portable-fs/meta.yaml
> DEV: portable-fs packaged

- recipes-tag/analysis/meta.yaml
> ipyvolume added

- recipes-tag/scikit-beam/meta.yaml
Test works fine under this version.
> skbeam new version 0.0.12

- scripts/nsls2-dev-build.sh
- scripts/nsls2-tag-build.sh
there is some error between py36 conda and build.py.
To be figured out later.
> DEV: use python3.5-based conda to build

- recipes-tag/chxtools/meta.yaml
> Update chxtools version.

- recipes-tag/oscars/meta.yaml
local build runs ok. https://github.com/NSLS-II/lightsource2-recipes/issues/205#issuecomment-335983026
> add oscars

- recipes-tag/oscars/meta.yaml
@dhidas  next time we only need to update version number based on the new recipe.
> DEV: simplified version for oscars, depending on github release

- recipes-dev/hkl/build.sh
- recipes-dev/hkl/meta.yaml
A version bump for hkl package
> Upgrade hkl version to 5.0.0.2173

- recipes-tag/bluesky/meta.yaml
- recipes-tag/ophyd/meta.yaml
> DEV: new version of bluesky and ophyd

- recipes-tag/bluesky/meta.yaml
- recipes-tag/ophyd/meta.yaml
1.0.0 is ready to build as previous versions are done according to https://github.com/NSLS-II/lightsource2-recipes/pull/216
> v1.0.0 for bluesky and ophyd

- recipes-tag/analysis/meta.yaml
- recipes-tag/collection/meta.yaml
There may be additional revisions before we deploy but this
is good to merge.
- Bump the version number.
- Add @dhidas 'oscars' package to the standard 'analysis' env.
- Also add 'dask' and 'distributed'.
> Draft update for 18Q1.

- recipes-tag/hklpy/meta.yaml
> ENH: add missing pygobject3 dep

- recipes-tag/hdf5-lz4/build.sh
Based on conversation in Slack.
> FIX: correct HDF5_PLUGIN_PATH to use $CONDA_PREFIX

- recipes-tag/chxtools/meta.yaml
Updated chxtools v2.0.1. There is a lot of work to do, but it's a good step towards usability and reproducibility.
> Updated chxtools v2.0.1

- recipes-tag/eiger-io/meta.yaml
> Bump eiger-io version

- recipes-tag/isstools/meta.yaml
> Bump isstools

- recipes-tag/isstools/meta.yaml
add requirements from discussion in #229
> add requirements to isstools

- recipes-tag/pyCHX/meta.yaml
Rename chxanalys -> pyCHX in tags.
> REL: rename chxanalys -> pyCHX

- recipes-tag/analysis/meta.yaml
> Add dask-related deps.

- recipes-tag/pychx/meta.yaml
- scripts/nsls2-tag-build.sh
> BUG: lower case for pychx

- recipes-tag/chxtools/meta.yaml
DO NOT MERGE 
works built, loaded on chx workstation, but want to finish the whole profile update process first
> Updated dependencies

- scripts/mirror-to-nsls2.sh
- scripts/mirror.py
> more platforms included

- recipes-tag/scikit-beam/meta.yaml
> scikit-beam version bump

- recipes-tag/analysis/meta.yaml
- recipes-tag/collection/meta.yaml
**DO NOT MERGE UNTIL WE ARE READY TO RELEASE 2018-1.1.** All
additions to 2018-1.1 should be added on this PR. Merging will
trigger the builder.
This PR includes commits from #245. #245 should be merged first.
> Bump version number and add fabio.

- recipes-tag/07-bm-qas-collection/meta.yaml
Add QAS-specific packages (just `isstools` for now).
> Added QAS collection

- recipes-tag/pyxdameraulevenshtein/meta.yaml
- recipes-tag/xpdview/meta.yaml
Add some dependencies required by xpd. taken from conda-forge.
@CJ-Wright
> Added xpd dependencies: xpdview, pyxdameraulevenshtein

- recipes-tag/04-id-isr-analysis/meta.yaml
fix to analysis metapackage
@danielballan
> Fixed analysis metapackage

- recipes-tag/eiger-io/meta.yaml
> Bump eiger-io build number

- recipes-tag/protobuf/PR_4124.patch
- recipes-tag/protobuf/bld.bat
- recipes-tag/protobuf/build.sh
- recipes-tag/protobuf/meta.yaml
This is required as a dependency of the new mysql connector.
> Pull in protobuf from conda-forge

- recipes-tag/oscars/meta.yaml
> bugfix version for oscars

- recipes-tag/oscars/meta.yaml
> up to micro-version 20

- recipes-tag/abbix_analysisstore/meta.yaml
- recipes-tag/conftrak/meta.yaml
> add abbix_analysisstore

- recipes-tag/historydict/meta.yaml
> update historydict (fixed a bug)

- recipes-tag/tomopy/meta.yaml
> tomopy from conda-forge

- recipes-tag/peakutils/meta.yaml
Useful package for detection of 1D peaks. Currently used at SMI. Taken from https://github.com/conda-forge/peakutils-feedstock/blob/master/recipe/meta.yaml. Resolves #288.
Related links:
- https://bitbucket.org/lucashnegri/peakutils
- https://anaconda.org/GSECARS/peakutils
- https://pypi.org/project/PeakUtils/
Attn @licode
> Add peakutils package

- recipes-tag/12-id-smi-analysis/meta.yaml
- recipes-tag/12-id-smi-collection/meta.yaml
Added SMI extra packages (`peakutils` at the moment).
@licode
> Add SMI extra packages

- recipes-tag/11-bm-cms-collection/meta.yaml
- recipes-tag/natsort/meta.yaml
> Added natsort dep for CMS

- recipes-tag/srw/build.sh
- recipes-tag/srw/meta.yaml
> Add SRW package

- recipes-tag/srw/build.sh
- recipes-tag/srw/meta.yaml
> SRW: reduce the size of the package

- recipes-tag/oscars/meta.yaml
Now has time-dependent E&B input fields.  RK4 step splitting for numerical stability in high E-fields.
> OSCARS minor version change

- recipes-tag/zbar/build.sh
- recipes-tag/zbar/meta.yaml
> zbar .so library for pyzbar (reading QR codes)

- recipes-tag/11-id-chx-analysis/meta.yaml
add pytables for chx analysis environment
> addpytables

- recipes-tag/hklpy/meta.yaml
hkl py fix: should not be string python dep
> remove strict dep

- recipes-tag/eiger-io/meta.yaml
bump eiger-io from addition of a `frame_num` datum kwarg for a different type of read [here](https://github.com/NSLS-II/eiger-io/pull/14).
> bump eiger-io

- recipes-tag/07-bm-qas-collection/meta.yaml
> Added pykafka for QAS

- recipes-tag/08-id-iss-analysis/meta.yaml
> Iss analysis

- scripts/build.py
- scripts/nsls2-tag-build.sh
Fix Numpy version in other places which weren't touched by #312.
> FIX: NumPy version now is 1.14

- recipes-tag/07-bm-qas-collection/meta.yaml
qas should use kafka-python instead
> change kafka to kafka-python

- recipes-tag/pysmbc/meta.yaml
> updated pysmbc

- recipes-tag/pypdf2/meta.yaml
Attn: @tacaswell @danielballan 
Build locally with https://hub.docker.com/r/nsls2/debian-with-miniconda/, tests pass successfully.
> Add pypdf2 recipe

- recipes-tag/xraylarch/meta.yaml
> Fix xraylarch 0.9.37 package

- recipes-tag/bluesky-kafka/meta.yaml
> Added bluesky kafka

- recipes-tag/caproto/meta.yaml
- recipes-tag/curio/meta.yaml
- recipes-tag/netifaces/meta.yaml
I tested that this builds on frejya.
> Add caproto and its deps (cargo-culted from conda-forged)

- recipes-tag/analysis/meta.yaml
- recipes-tag/collection/meta.yaml
Should be merged after we're happy with most packages. should be done after #308  as well
> Update metapackages for 2018C2.0

- recipes-tag/collection/meta.yaml
> MNT: add nsls-ii as collection dependency

- recipes-tag/nslsii/meta.yaml
Attn: @danielballan @tacaswell
> Bump nslsii to 0.0.3 (with TwoButtonShutter already)

- recipes-tag/regolith/meta.yaml
- recipes-tag/shed/meta.yaml
- recipes-tag/streamz/meta.yaml
- recipes-tag/xpdacq/meta.yaml
- recipes-tag/xpdan/meta.yaml
- recipes-tag/xpdtools/meta.yaml
I have one more on the way but I'll most likely get it in first thing tomorrow.
> xpd cycle 2 2018

- recipes-tag/23-id-1-csx1-analysis/meta.yaml
- recipes-tag/23-id-1-csx1-collection/meta.yaml
- recipes-tag/hkl/meta.yaml
- recipes-tag/hklpy/meta.yaml
> fixed csx packages

- recipes-tag/23-id-1-csx1-analysis/meta.yaml
- recipes-tag/23-id-1-csx1-collection/meta.yaml
- recipes-tag/hkl/meta.yaml
- recipes-tag/hklpy/meta.yaml
need to update build numbers from #362
> bump build number

- recipes-tag/03-id-hxn-collection/meta.yaml
- recipes-tag/05-id-srx-collection/meta.yaml
Use the same versioning style for both HXN and SRX metapackages.
> Update HXN and SRX metapackages

- scripts/nsls2-tag-build.sh
> Restore building with Python 3.5

- recipes-tag/oscars/meta.yaml
Hello.  Also works in python 3.7.
> [oscars] update version and bugfix for input trajectories

- recipes-tag/18-id-fxi-collection/meta.yaml
Adding reportlab as requested by Ming.
> Add reportlab

- recipes-tag/srw/meta.yaml
> SRW: test build to test local conda server

- scripts/nsls2-dev-build.sh
- scripts/nsls2-tag-build.sh
> DEV: no py2

- recipes-tag/pycxdgui/meta.yaml
Added pycxdgui. tested locally pushing to my channel. worked.
> Addded pycxdgui recipe

- recipes-tag/hxntools/meta.yaml
also fill out more dependencies
> REL: bump version of hxntools to build

- recipes-tag/fabio/meta.yaml
so we get it with numpy 1.15 and py37
> MNT: force rebuild of fabio

- recipes-tag/databroker/meta.yaml
- recipes-tag/suitcase/meta.yaml
build py37 for suitcase and databroker.
> DEV: py37 version missing

- recipes-tag/libnetcdf/0001-Fix-bug-Index-exceeds-dimension-bound.patch
- recipes-tag/libnetcdf/0002-run_get_hdf4_files.sh-Use-curl-if-wget-fails-macOS-d.patch
- recipes-tag/libnetcdf/0003-Add-find_package-Threads-REQUIRED-to-CMakeLists.txt.patch
- recipes-tag/libnetcdf/0004-Prefer-getenv-TOPSRCDIR-over-STRINGIFY-TOPSRCDIR.patch
- recipes-tag/libnetcdf/0005-Convert-some-c99-to-c89-by-hand.patch
- recipes-tag/libnetcdf/0006-Fix-tests-for-Windows-VS2008-define-__func__-as-__FU.patch
- recipes-tag/libnetcdf/0007-Fix-broken-test.patch
- recipes-tag/libnetcdf/0008-Finish-the-missing-code-to-handle-VS-in-test_common..patch
- recipes-tag/libnetcdf/bld.bat
- recipes-tag/libnetcdf/build.sh
- recipes-tag/libnetcdf/cross-linux.cmake
- recipes-tag/libnetcdf/higher_timeout.patch
- recipes-tag/libnetcdf/meta.yaml
- recipes-tag/libnetcdf/prevent_MS_runtime_libs_being_installed_again.patch
- recipes-tag/libnetcdf/run_test.sh
- recipes-tag/netcdf4/.circleci/checkout_merge_commit.sh
- recipes-tag/netcdf4/.gitattributes
- recipes-tag/netcdf4/.github/CONTRIBUTING.md
- recipes-tag/netcdf4/.github/ISSUE_TEMPLATE.md
- recipes-tag/netcdf4/.github/PULL_REQUEST_TEMPLATE.md
- recipes-tag/netcdf4/.gitignore
- recipes-tag/netcdf4/COPYING
- recipes-tag/netcdf4/LICENSE.txt
- recipes-tag/netcdf4/bld.bat
- recipes-tag/netcdf4/build.sh
- recipes-tag/netcdf4/meta.yaml
- recipes-tag/netcdf4/run_test.py
> pin netcdf4 to hdf5=1.10.0

- recipes-tag/11-id-chx-analysis/meta.yaml
- recipes-tag/pychx/meta.yaml
update version and dependency of 11id-analysis
> Pychx update

- recipes-tag/11-id-chx-analysis/meta.yaml
@mrakitin  can you take a look for this new PR? Thanks!
> Update 11id with papermill

- recipes-tag/pystackreg/meta.yaml
Responding to review comments from @mrakitin. All are related to hygiene;
none will affect the build product.
> Corrections to pystackreg recipe.

- recipes-tag/23-id-1-csx1-collection/meta.yaml
> CSX: collection metapackage update

- recipes-tag/caproto/meta.yaml
Merge #668 first and let that build.
> Bump caoroto to 0.3.4.

- recipes-tag/sasview/meta.yaml
Successfully built in a Docker container locally.
Corresponding conda-forge PR: https://github.com/conda-forge/sasview-feedstock/pull/3.
> New version of sasview (stable v5.0.0)

- recipes-tag/librdkafka/build.sh
- recipes-tag/librdkafka/meta.yaml
Edited by @mrakitin: it's a dependency of both pykafka (#685) and confluence-kafka (#687).
> BLD: Add librdkafka

- recipes-tag/kazoo/meta.yaml
> BLD: add kazoo

- recipes-tag/08-bm-tes-collection/meta.yaml
xref https://controlsweb.nsls2.bnl.gov/trac/ticket/3531.
> TES: add PyXRF dependency

- recipes-tag/python-confluent-kafka/meta.yaml
https://github.com/confluentinc/confluent-kafka-python/releases
> BLD: add python-confluent-kafka

- recipes-tag/pykafka/meta.yaml
https://github.com/Parsely/pykafka/releases
2.8.0 latest release for pykafka
> BLD: meta file for pykafka

- recipes-tag/11-bm-cms-collection/meta.yaml
> BLD: add lxml and update cycle

- recipes-tag/collection/meta.yaml
> BLD: Update collection package to version 2019C3.0

- recipes-tag/tomopy/meta.yaml
This is copy from conda-forge
https://github.com/conda-forge/tomopy-feedstock/blob/master/recipe/meta.yaml
> BLD: tomopy 1.5.0

- recipes-tag/16-id-lix-analysis/meta.yaml
Add, all exist in lightsource2-recipe
`py4xs`
`lmfit`
> 16id Package needed for 2019C3.0

- recipes-tag/pychx/meta.yaml
Based on new tag and release here and CHX 11 ID request
https://github.com/NSLS-II-CHX/pyCHX/releases
> BLD: Update pychx

- scripts/build.py
- scripts/nsls2-tag-build.sh
- manually handle dependencies
- remove installing conda-execute
> MNT: try to update our build script

- recipes-dev/pycentroids/meta.yaml
- recipes-tag/lmfit-c/meta.yaml
- recipes-tag/pycentroids/meta.yaml
I added the tests to the conda build script. With this not being a pure python module I like going past the import stage to test to make sure that the cxx modules were compiled ok.
> Added tests to pycentroids

- recipes-tag/pycentroids/meta.yaml
Updated version to 1.8. Attn @ke-zhang-rd and @mrakitin
> Bump version to 1.8

- recipes-tag/py4xs/meta.yaml
> MNT: update py4xs to current latest

- recipes-tag/bluesky-darkframes/meta.yaml
> Add bluesky-darkframes recipe.

- recipes-tag/lmfit-c/meta.yaml
@mrakitin This is the updated version of `lmfit-c` with the correct hash....
> Updated hash for lmfit-c
